#include<stdio.h>
#include<conio.h>
int main()
{
    int mat[3][3],trans[3][3],i,j,k;
    printf("\n  The program will create transpose of a given matrix.\n\n  ");

    printf("Enter values in the matrix : \n");
    for(i=0;i<3;i++)
        for(j=0;j<3;j++)
        {
            printf("  ");
            scanf("%d",&mat[i][j]);
        }

    printf("\n  Matrix made by the user : \n");
    for(i=0;i<3;i++)
    {
        printf("\n  ");
        for(j=0;j<3;j++)
            printf("[%d]. ",mat[i][j]);
    }

    for(i=0;i<3;i++)
        for(j=0;j<3;j++)
            trans[j][i]=mat[i][j];

    printf("\n\n  Transpose generated by the program : ");
    for(i=0;i<3;i++)
    {
        printf("\n  ");
        for(j=0;j<3;j++)
            printf("[%d]. ",trans[i][j]);
    }

    printf("\n\n  Press any key to exit program.\n\n  ");
    getch();
    return(0);
}
